Repository warmachine028/memories, pull requests merged in 2022-10, with the labels that each got.

#19 Added CONTRIBTING.md and CODE_OF_CONDUCT.md file
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted

#23 Add Contributors Pannel
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#24 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/other.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted
