Repository warmachine028/memories, pull requests merged in 2023-10, with the labels that each got.

#84 fixed console warning bug
  client/src/index.jsx
Labels: bug, hacktoberfest, hacktoberfest-accepted, complete, 🛠 goal: fix, 🐞 bug

#81 #79 bug Fixed :Outlines are not visible in dark mode are fixed
  client/src/components/Input/index.jsx
  client/src/components/Input/styles.js
Labels: hacktoberfest, UI/UX 🖍️, 🛠 goal: fix, 🐞 bug

#90 fixed duplicate module imports
  client/src/components/PostDetails/CommentSection/index.jsx
  client/src/components/ScrollToTop/index.jsx
  client/src/components/User/Cards/index.jsx
  client/src/components/User/Details/index.jsx
Labels: hacktoberfest, hacktoberfest-accepted, 🛠 goal: fix, 🐞 bug

#96 Fix: Tags functionality readded
  client/package-lock.json
  client/package.json
  client/src/components/Form/Form.jsx
  client/src/components/Search/Search.jsx
Labels: hacktoberfest, hacktoberfest-accepted, UI/UX 🖍️, 🛠 goal: fix, 🐞 bug

#98 Fixed tags input size
  client/src/components/Form/Form.jsx
  client/src/components/Search/Search.jsx
Labels: hacktoberfest, hacktoberfest-accepted, 🛠 goal: fix, 🐞 bug

#99 fix: change SwipeableViews import in UserDetails index file (#89)
  client/src/components/Paginate/Paginate.jsx
  client/src/components/PostDetails/CommentSection/index.jsx
  client/src/components/PostDetails/PostDetails.jsx
  client/src/components/PostDetails/RecommendedPosts.jsx
  client/src/components/User/Details/index.jsx
  client/src/index.css
Labels: hacktoberfest, hacktoberfest-accepted, 🛠 goal: fix, 🐞 bug

#103 refactor: avoid square-bracket notation when accessing properties
  client/src/components/UserIcon/avatar.js
Labels: hacktoberfest, hacktoberfest-accepted, 🛠 goal: fix, 🐞 bug

#101 fix: recover tab navigation functionality in user detail sections
  client/src/components/User/Details/index.jsx
  client/src/hooks.js
Labels: hacktoberfest, hacktoberfest-accepted, 🛠 goal: fix, 🐞 bug

#108 feat: light mode colors enhancements
  client/src/components/PostDetails/CommentSection/index.jsx
  client/src/components/PostDetails/CommentSection/styles.js
  client/src/components/PostDetails/PostDetails.jsx
  client/src/components/PostDetails/styles.js
  client/src/components/Search/Search.jsx
Labels: enhancement, hacktoberfest, feature

#111 fix: fixing get user in user controller
  server/controllers/user.js
Labels: hacktoberfest, 🛠 goal: fix, 🐞 bug

#106 fix: updated regExptext instead of stringmatch and few anti pattern
  README.md
  client/src/App/App.jsx
  client/src/api/index.js
  client/src/components/Form/Form.jsx
  client/src/components/Home/index.jsx
  client/src/components/Navbar/Navbar.jsx
  client/src/components/PostDetails/CommentSection/index.jsx
  client/src/components/Search/Search.jsx
  client/src/components/User/Details/index.jsx
  client/src/components/User/TabPage/index.jsx
  client/src/hooks.js
  client/src/reducers/auth.js
  client/src/reducers/posts.js
  client/src/service-worker.js
  client/src/serviceWorkerRegistration.js
  server/controllers/user.js
Labels: hacktoberfest, 🛠 goal: fix, 🐞 bug

#110 feat: darkMode for user profile has been done
  client/package-lock.json
  client/src/components/User/Cards/index.jsx
  client/src/components/User/Cards/styles.js
  client/src/components/User/Details/index.jsx
  client/src/components/User/Details/styles.js
Labels: enhancement, hacktoberfest, feature

#113 fix: added Vite to README with logo as well as formatted code with prettie…
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, 🛠 goal: fix, 🐞 bug

#117 fix: resolved variable shadowing and a unreachable line in the code
  README.md
  client/src/components/Form/Form.jsx
  client/src/components/User/Details/index.jsx
  client/src/service-worker.js
Labels: hacktoberfest, 🛠 goal: fix, 🐞 bug

#119 feat: added dynamic tags suggestion and fixed search by tag
  client/package-lock.json
  client/src/api/index.js
  client/src/components/Form/Form.jsx
  client/src/components/Search/Search.jsx
  server/.env.example
  server/controllers/posts.js
  server/routes/posts.js
Labels: enhancement, hacktoberfest, 💻 aspect: code, 💡feature

#122 docs: hacktoberfest banner replacement
  README.md
Labels: documentation, hacktoberfest, 📄 aspect: text

#123 fix: loading for pagination component added!!
  client/src/components/Paginate/Paginate.jsx
Labels: hacktoberfest

#124 fix: pagination loading style updated
  client/src/components/Paginate/Paginate.jsx
  client/src/components/Paginate/styles.js
Labels: hacktoberfest, 🛠 goal: fix, 🐞 bug

#126 feat: dark Mode for the profile Page Added
  client/package-lock.json
  client/src/components/User/Details/index.jsx
  package-lock.json
Labels: enhancement, hacktoberfest, ⭐ goal: addition, 💡feature
