Repository warmachine028/memories, pull requests merged in 2023-09, with the labels that each got.

#67 fix(posts): sanitize chars in all occurrences
  client/src/actions/posts.js
Labels: 🛠 goal: fix

#69 Change nodemon from server dependencies to dev dependencies
  server/package-lock.json
  server/package.json
Labels: complete, merged

#71 Improvement link spelling corrected in README.md file
  README.md
Labels: documentation, pending, complete, 📄 aspect: text, 🛠 goal: fix
